"""empty message

Revision ID: e522865df20b
Revises: 51c61fe27855
Create Date: 2024-08-03 01:06:22.827484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e522865df20b'
down_revision: Union[str, None] = '51c61fe27855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_post_like', 'likes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_post_like', 'likes', type_='unique')
    # ### end Alembic commands ###
